name: MagicTeleport
version: '${project.version}'
main: fr.sixpixels.magicteleport.MagicTeleport
api-version: '1.20'

commands:
  magicteleport:
    aliases: [mtp]
    description: Give a teleportation block to a player
